flake: {
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.programs.direnv.new;
  flakePkgs = flake.packages.${pkgs.stdenv.hostPlatform.system};

  configFileContent = ''
    # Generated by direnv-new home-manager module
    DIRENV_NEW_CREATE_GIT=${lib.boolToString cfg.config.createGit}
    DIRENV_NEW_NO_IGNORE=${lib.boolToString cfg.config.ignoreGit}
    DIRENV_NEW_AUTOCOMPLETE=${lib.boolToString cfg.config.autocomplete}
    DIRENV_NEW_SILENT=${lib.boolToString cfg.config.silent}
  '';
in {
  options.programs.direnv.new = {
    enable = lib.mkEnableOption "direnv 'new' subcommand for scaffolding .envrc files";

    config = {
      createGit = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Initialize a git repository by default when creating .envrc.";
      };

      ignoreGit = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Do not write .direnv entry to .gitignore by default.";
      };

      autocomplete = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable nix package name autocomplete in bash completions.";
      };

      silent = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Suppress non-essential output from direnv-new.
          Note: this is also automatically respected at runtime when
          programs.direnv.silent is true (via DIRENV_LOG_FORMAT="").
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    programs.direnv = {
      enable = true;
      package = lib.mkDefault flakePkgs.default;
    };

    xdg.configFile."direnv-new/config".text = configFileContent;
  };
}
