flake: {
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.programs.direnv.new;
  direnvCfg = config.programs.direnv;
  flakePkgs = flake.packages.${pkgs.stdenv.hostPlatform.system};

  configFileContent = ''
    # Generated by direnv-new home-manager module
    DIRENV_NEW_CREATE_GIT=${lib.boolToString cfg.config.createGit}
    DIRENV_NEW_NO_IGNORE=${lib.boolToString cfg.config.ignoreGit}
    DIRENV_NEW_AUTOCOMPLETE=${lib.boolToString cfg.config.autocomplete}
    DIRENV_NEW_SILENT=${lib.boolToString cfg.config.silent}
  '';
in {
  options.programs.direnv.new = {
    enable = lib.mkEnableOption "direnv 'new' subcommand for scaffolding .envrc files";

    config = {
      createGit = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Initialize a git repository by default when creating .envrc.";
      };

      ignoreGit = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Do not write .direnv entry to .gitignore by default.";
      };

      autocomplete = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable nix package name autocomplete in bash completions.";
      };

      silent = lib.mkOption {
        type = lib.types.bool;
        default = direnvCfg.silent or false;
        defaultText = lib.literalExpression "config.programs.direnv.silent";
        description = ''
          Suppress non-essential output from direnv-new.
          Defaults to the value of programs.direnv.silent when set.
        '';
      };

      enableNixDirenv = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Enable nix-direnv integration.
          Required for 'use nix -p' and 'use flake' in generated .envrc files.
          Sets programs.direnv.nix-direnv.enable.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    programs.direnv = {
      enable = true;
      package = lib.mkDefault flakePkgs.default;
      nix-direnv.enable = lib.mkDefault cfg.config.enableNixDirenv;
    };

    xdg.configFile."direnv-new/config".text = configFileContent;
  };
}
